### ISSUE TITLE
Add ZeroTier transport

### ISSUE THREAD

**Issue by SysLabIT** [nanomsg/mangos-v2#83]
Hi,

Are there any plans for adding ZeroTier transport?
ETA?

**Comment by gdamore** [comment]
At the moment there are no plans.  Mangos is written in pure Go, and unfortunately ZeroTier is insufficiently documented in to reimplement (easily) in pure Go.  There is a C++ library with C stubs, that could be accessed via native bindings, but if you need to use ZeroTier you can *also* do so using an NNG proxy.

If there were a commercial case for making a mangos plugin transport (there is a transport API) as a separate modular project, which used the C library with Go wrappers, I could be convinced to do it.  But absent a significant commercial sponsor, I don't see it happening any time soon.

**Comment by SysLabIT** [comment]
Sure, thank you for fast reply.

**Comment by gdamore** [comment]
Btw, because of the licensing details of ZeroTier (GPL) it will not be possible to mix and match mangos and ZeroTier in the same distributed binary, as the Apache license and GPL are incompatible (a consequences of overly strict restrictions in the GPL).

At any rate, I'm closing this for now.  Contact me out of band if you want to seek doing this as a sponsored project.
